### ISSUE TITLE
Mega downloading is not working 

### ISSUE THREAD

**Issue by Niaz264** [majnurangeela/mirror-hunter-upstream#1]
I'm getting this error while downloading from mega.. I added my mega credentials but It’s not working 

NameError: name 'MEGA_KEY' is not defined

**Comment by majnurangeela** [comment]
OK It will be fixed

**Comment by majnurangeela** [comment]
The issue is fixed ! Thanks for reporting.
Note: Make sure MEGAREST env is True in config.env
